# basic options
title: Homepage
author: Me
email: none@yourbusiness.com
twitter_username: drivenbymetal
github_username: thrashing-maniac
description: My Project updates!

# Build Options
markdown: kramdown
theme: hydejack
